# Generated by Django 2.1.5 on 2019-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0002_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='name',
            field=models.CharField(default='Alex', max_length=100),
        ),
    ]
